### PR TITLE
Testbranch

### PR DESCRIPTION
**Pull request by pratik9333**
Fixed the issue, check it and you can merge it

### CODE REVIEW

**Comment by pratik9333** [comment]
Made changes @lmcjt37

**Comment by lmcjt37** [comment]
@pratik9333 I took a look at the package-lock.json file and it seems you installed the packages with an older npm version and this created a new diff using v1. 

So you could either uncommit the lockfile or upgrade your npm version and re-install the packages to address the issue.

**Comment by lmcjt37** [comment]
@pratik9333 nice, the tests are fixed. Lockfile still outstanding

- [ ] Revert lockfile

**Comment by pratik9333** [comment]
git reset 227ba263955b3ab0b63766bfe96e8a83d4aa5c5a -- package-lock.json
git add .
git commit -m "revert lockfile"
git push -f
@lmcjt37 
I Tried all these commands but its showing Everything up-to-date after pushing :(

**Pull request merged**
