### PR TITLE
Curated-fevicon

### PR DESCRIPTION
**Pull request by sowmiyeh**
PR for issue #243

### CODE REVIEW

**Comment by sowmiya-venkatesan** [comment]
> ~There are 3 png format images to replace at /public/assets/~
> 
> ~You should make sure they are like for like in name and size. I would expect there to be 3 file changes in this PR.~
> 
> ~Example logo-16.png is the name and is 16x16~
> 
> Just looking into this and the file should actually be named `favicon.ico` and be 64x64. The other logo pngs can then be deleted in favour of this.

Please check it now @lmcjt37

**Comment by lmcjt37** [comment]
Hi @sowmiya-venkatesan 

Looks like the size is right.

But the file name should be `favicon.ico` without the `.png` format as this is a `ico` format file. Also need to remove the logo assets still.

**Comment by sowmiya-venkatesan** [comment]
> Hi @sowmiya-venkatesan
> 
> Looks like the size is right.
> 
> But the file name should be `favicon.ico` without the `.png` format as this is a `ico` format file. Also need to remove the logo assets still.

Done with replacing logos also with correct format

**Comment by sowmiya-venkatesan** [comment]
Thanks for merging it, it would be great if you can label it as accepted

**Comment by lmcjt37** [comment]
Please check your Hacktoberfest profile page as the merge should count towards your PR count.

**Comment by sowmiya-venkatesan** [comment]
> Please check your Hacktoberfest profile page as the merge should count towards your PR count.

Yes it is, Thank you !!

**Pull request merged**
