### PR TITLE
reafactor: App.js and tests

### PR DESCRIPTION
**Pull request by jason1985**
# Work In Progress
This PR addresses #247 

@lmcjt37 `App.js` works fine however I'm having trouble refactoring some of the tests in `App.test.js`.
I have 4 of the tests working but I'm not sure how to go about refactoring the other tests yet.
If you have any advice let me know.
Thanks!
## How I'm testing
I added `testing` & `testType` props to `<App />` that are `false` by default but used in tests with:

```js
  const wrapper = mount(<App testing={true} testType="no data" />); // tests for 'no content'
```
Handled in `App.js` with:
```js
if (testing === true) {
  if (testType === 'no data') {
    setContent([]); // testing - 'can't load the data'
  }
}
```
## Passing Tests
- 'render all initial child components'
- 'renders error component for no search results'
- 'renders error component when it can't load the data'
- 'snapshot changes when input change'

image

### CODE REVIEW

**Comment by lmcjt37** [comment]
@jason1985 

Easiest thing to do is create two functional components, one is the parent(default export) that will handle hooks, methods and passing data. This parent then returns the second component which renders the actual components and is essentially dumb as it simply receives everything it requires and you export this child and test against this instead.

To test the helper methods, these could possibly be abstracted outside the scope of the parent also and exported in the same way then you can simply import these too and test them easily that way.

(Coding this on my phone just to unblock you, any questions or confusion just ask and I'll try get to my computer to reply next)

export child = ({ data, onAction }) => <Example>
    {data} // use the data somehow
    <button onClick={onAction} />
  </Example>

export default parent = () => {

  let data = null // example null data
  const handleAction = () => {}

  return <ChildComponement data={data} onAction={handleAction} />
}

**Comment by lmcjt37** [comment]
Looks good to me.

The other thing I would probably do is keep the mocks simple and clean, by defining them once and not mutating them.

The `allContentLength` value you could or would define when declaring the variable. Then you don't need to set within the mock function. Also because you already know the value the first expectation is redundant.

So then you call the helper function with a year and the mocks carry out the expectations when called. Those expectations would test that the change has succeeded.

**Comment by jason1985** [comment]
@lmcjt37 thanks. Sorry if I'm asking too many questions. 😅 

Given this function:
```js
export const toggleFilter = (setShowFilters, showFilters) => {
  setShowFilters(!showFilters);
};
```
I want to test that when `toggleFilter` is passed `false` that it sets `showFilters` to `true` and vice versa.
So to test these two cases, I wrote this test:
```js
it('calls toggleFilter correctly', () => {
  let setShowFilters = jest.fn().mockImplementation(arg => {
    expect(arg).toBeFalsy();
  });
  let showFilters = true;

  toggleFilter(setShowFilters, showFilters);

  setShowFilters = jest.fn().mockImplementation(arg => {
    expect(arg).toBeTruthy();
  });
  showFilters = false;

  toggleFilter(setShowFilters, showFilters);
});
```
Is there a cleaner better way to do this without mutating and writing the mock `setShowFilters` function twice?
Or should I just write to separate `it` statements like this:
```js
it('calls toggleFilter with true correctly', () => {
  const setShowFilters = jest.fn().mockImplementation(arg => {
    expect(arg).toBeFalsy();
  });
  let showFilters = true;

  toggleFilter(setShowFilters, showFilters);
});

it('calls toggleFilter with false correctly', () => {
  const setShowFilters = jest.fn().mockImplementation(arg => {
    expect(arg).toBeTruthy();
  });
  showFilters = false;

  toggleFilter(setShowFilters, showFilters);
});
```

Thank you.

**Comment by lmcjt37** [comment]
@jason1985 Happy with the work and tested locally...all checks out! Great effort 🚀

**Pull request merged**
