### PR TITLE
244 refactor components

### PR DESCRIPTION
**Pull request by jason1985**
# Work In Progress
This PR addresses #244
As of now just refactored 2 class components to functional components. (`filterBar.js` & `header.js`)

### CODE REVIEW

**Comment by jason1985** [comment]
@lmcjt37 let me know if I need to change anything.

Also I went ahead and refactored `App.js` to use `useState` & `useEffect` hooks, but I haven't committed it yet.
It seems to be working fine locally however it wont be able to pass the tests in `App.test.js` because it has some tests for a class based component:
https://github.com/lmcjt37/curated-tv-and-film/blob/d2c1b8460c098caa010e273651540d7cc121e8ee/src/__tests__/App.test.js#L26-L29

Thanks.

**Comment by lmcjt37** [comment]
@jason1985 what you've pushed so far looks great.

I would say don't commit the changes around app.js. Those could be done in a separate PR where the tests should be fixed also. It would be a blocking change as it would break the pipeline build and deploy.

I can raise another PR for this now so you can tackle that also if you like?

**Comment by lmcjt37** [comment]
@jason1985 Ticket for app.js here https://github.com/lmcjt37/curated-tv-and-film/issues/247

**Comment by jason1985** [comment]
@lmcjt37 yes.

**Pull request merged**
