### PR TITLE
Added in alphabetical sorting for titles

### PR DESCRIPTION
**Pull request by CometS1**
A small change that sorts each tv show/film alphabetically by their titles

### CODE REVIEW

**Comment by lmcjt37** [comment]
Need to update the snapshots as you've changed the expected output of content.js :)

**Comment by CometS1** [comment]
How do you update the snapshots?

**Comment by lmcjt37** [comment]
To update them, you simple run the tests `npm test` this will probably show failing tests.

You should then be able to use the command prompt to simply press `u` this will update the snapshots and re-run the tests again.

**Comment by lmcjt37** [comment]
@CometS1 I have updated your branch to resolve conflicts from other merges, you may notice commits on your forked repo.

If you would like to add yourself to the contributors.md file then create a new PR. 

Good work 👍

**Pull request merged**
